# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{Spy-Vs-Spy}
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristan \"Krispy\" Uccello"]
  s.date = %q{2009-11-23}
  s.description = %q{Rack middleware to detect and provide more detail on the requesting user agent edit}
  s.email = %q{kuccello@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    "Change.log",
     "LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "lib/spy_vs_spy.rb",
     "test/firefox/firefox-3.1b2.txt",
     "test/firefox/firefox-3.1b2pre.txt",
     "test/firefox/firefox-3.1b3.txt",
     "test/firefox/firefox-3.1b3pre.txt",
     "test/firefox/firefox-3.5.1.txt",
     "test/firefox/firefox-3.5.12.txt",
     "test/firefox/firefox-3.5.2.txt",
     "test/firefox/firefox-3.5.3.txt",
     "test/firefox/firefox-3.5.3pre.txt",
     "test/firefox/firefox-3.5.4.txt",
     "test/firefox/firefox-3.5.5.txt",
     "test/firefox/firefox-3.5.txt",
     "test/firefox/firefox-3.5b4.txt",
     "test/firefox/firefox-3.5b4pre.txt",
     "test/firefox/firefox-3.6.txt",
     "test/firefox/firefox-3.6a1pre.txt",
     "test/firefox/firefox-3.6b1.txt",
     "test/firefox/firefox-3.8.txt",
     "test/msie/msie-5.5.txt",
     "test/msie/msie-5.5b1.txt",
     "test/msie/msie-6,0.txt",
     "test/msie/msie-6.0.1.txt",
     "test/msie/msie-6.0.txt",
     "test/msie/msie-6.0b.txt",
     "test/msie/msie-6.1.txt",
     "test/msie/msie-7.0.txt",
     "test/msie/msie-7.0b.txt",
     "test/msie/msie-8.0.txt",
     "test/safari/safari-1.0.3.txt",
     "test/safari/safari-1.0.txt",
     "test/safari/safari-1.2.2.txt",
     "test/safari/safari-1.2.3.txt",
     "test/safari/safari-1.2.4.txt",
     "test/safari/safari-1.2.txt",
     "test/safari/safari-1.3.1.txt",
     "test/safari/safari-1.3.2.txt",
     "test/safari/safari-1.3.txt",
     "test/safari/safari-2.0.1.txt",
     "test/safari/safari-2.0.2.txt",
     "test/safari/safari-2.0.3.txt",
     "test/safari/safari-2.0.4.txt",
     "test/safari/safari-2.0.txt",
     "test/safari/safari-3.0.1.txt",
     "test/safari/safari-3.0.2.txt",
     "test/safari/safari-3.0.3.txt",
     "test/safari/safari-3.0.4.txt",
     "test/safari/safari-3.0.txt",
     "test/safari/safari-3.1.1.txt",
     "test/safari/safari-3.1.2.txt",
     "test/safari/safari-3.1.txt",
     "test/safari/safari-3.2.1.txt",
     "test/safari/safari-3.2.2.txt",
     "test/safari/safari-3.2.3.txt",
     "test/safari/safari-3.2.txt",
     "test/safari/safari-4.0.1.txt",
     "test/safari/safari-4.0.2.txt",
     "test/safari/safari-4.0.3.txt",
     "test/safari/safari-4.0.txt",
     "test/safari/safari-4.0dp1.txt",
     "test/safari/safari.txt",
     "test/ss-test.rb"
  ]
  s.homepage = %q{http://github.com/kuccello/Spy-Vs-Spy}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Rack middleware to detect and provide more detail on the requesting user agent edit}
  s.test_files = [
    "test/ss-test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

